### ISSUE TITLE
Using Middleware within Scope and Get

### ISSUE THREAD

**Issue by iraycd** [rezeus/korauter#2]
Can you give similar snippets on how to implement.

```javascript
  posts.scope('Post', '/:postId', postMiddleware1, postMiddleware2, (post) => {
    // get the 'postId' via `ctx.params`
    post.get('ViewPost', '/', PostsController.view);

    post.scope('Comments', '/comments', postCommentMiddleware1, postCommentMiddleware2, (comments) => {
      comments.get('Index', '/', postCommentIndexMW, CommentsController.index);
      // also get the 'commentId' via `ctx.params`
      comments.get('View', '/:commentId', CommentsController.view);
    });
  });
```

Thank you.

**Comment by ozanmuyes** [comment]
Korauter is not supporting middlewares in route definitions (i.e. `router.get()`) and will not. You can consult [this section](https://github.com/rezeus/korauter#koa-router) of the documentation to see conditionally using a middleware with Korauter.

The middlewares in question are presumed written by you/your team. Thus it should be easy to add condition check for `ctx.route.meta.XXX` and then either run the middleware or skip it for the route.
Koa middlewares, on the other hand, are to be registered out of the Korauter scope - preferably before registering Korauter middleware against Koa via `router.resolve()` and `router.handle()` duo or `router.routes()`.

The reason that no middleware support in route definition comes from design principles; since Korauter is a middleware for Koa, it shouldn't mess with (i.e. manage execution) other middlewares (either with Koa or application middlewares). They are on the same level in my point of view.

---

All those being said there is an escape hatch, Koa uses [a library to compose middlewares](https://github.com/koajs/compose) (`koajs/compose`). A middleware is essentially a function, like the one a controller exports. What you can do is install (or re-use the one that Koa installs) `koajs/compose` package and compose middleware and controller functions before handing them to the route definition. Please see the gist [here](https://gist.github.com/ozanmuyes/78d7a09f738196ab5f8155c5c2cd1444/revisions#diff-4e54e674905c20773263ef6d3a3cba2b).

---

I am going to left this issue open, feel free to ask more question in this context or create a new issue about anything else. Thanks for your interest, have a good day.
